### ISSUE TITLE
ImportError with matplotlib 3.9

### ISSUE THREAD

**Issue by Deepthought73** [CommonRoad/commonroad-io#4]
I updated matplotlib from 3.8 to 3.9 and got this ImportError in the file commonroad/visualization/traffic_sign.py:

In commonroad/visualization/traffic_sign.py, line 8, in <module>
    from matplotlib.axes import Axes, mtext
ImportError: cannot import name 'mtext' from 'matplotlib.axes'

It's still working with matplotlib 3.8.4

**Comment by smaierhofer** [comment]
solved in the develop branch
